default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", nil) %>
  password: <%= ENV.fetch("DB_PASSWORD", nil) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "wedding_gallery_api_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "wedding_gallery_api_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "wedding_gallery_api_production") %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME", "wedding_gallery_api_production") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME", "wedding_gallery_api_production") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_NAME", "wedding_gallery_api_production") %>_cable
    migrations_paths: db/cable_migrate
